# Generated by Django 6.0.7 on 2026-07-21 10:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('age', models.CharField(blank=True, choices=[('JP', 'Jeune'), ('A', 'Adulte'), ('V', 'Vieux')], max_length=2, null=True)),
                ('etat_site', models.CharField(blank=True, choices=[('ISO', 'isolé'), ('TOF', 'touffes')], max_length=3, null=True)),
                ('etat_sante', models.CharField(blank=True, choices=[('B', 'Bon'), ('MO', 'Moyen'), ('MA', 'Mauvais'), ('MR', 'Mort')], max_length=2, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1, null=True)),
                ('variete', models.CharField(blank=True, max_length=100, null=True)),
                ('ligne', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('code_uni', models.CharField(blank=True, max_length=100, null=True)),
                ('code_local', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palms', to='parcels.parcelle')),
            ],
            options={
                'ordering': ['ligne', 'numero'],
            },
        ),
    ]
