# Generated by Django 6.0.7 on 2026-07-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palm',
            name='nombre_rejets',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nombre de rejets (uniquement pour les touffes — etat_site=TOF)', null=True),
        ),
    ]
