# Generated by Django 6.0.7 on 2026-08-08 11:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palms', '0003_fix_code_uni_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palm',
            name='age',
            field=models.CharField(choices=[('JP', 'Jeune'), ('A', 'Mature'), ('V', 'Vieux')], max_length=2),
        ),
        migrations.AlterField(
            model_name='palm',
            name='etat_site',
            field=models.CharField(choices=[('ISO', 'Isolé'), ('TOF', 'Touffes'), ('V', 'Vide')], max_length=3),
        ),
        migrations.AlterField(
            model_name='palm',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='palm',
            name='nombre_rejets',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nombre de rejets (uniquement pour les touffes)', null=True),
        ),
    ]
