# Generated by Django 6.0.7 on 2026-08-02 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0002_alter_parcelle_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSentinel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_acquisition', models.DateField()),
                ('produit_id', models.CharField(blank=True, max_length=200)),
                ('nuage_pct', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('telechargement', 'Téléchargement'), ('traitement', 'Traitement'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20)),
                ('chemin_b04', models.CharField(blank=True, max_length=500)),
                ('chemin_b08', models.CharField(blank=True, max_length=500)),
                ('chemin_b11', models.CharField(blank=True, max_length=500)),
                ('message_erreur', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_sentinel', to='parcels.parcelle')),
            ],
            options={
                'ordering': ['-date_acquisition'],
            },
        ),
        migrations.CreateModel(
            name='IndiceSpectral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ndvi_min', models.FloatField(blank=True, null=True)),
                ('ndvi_max', models.FloatField(blank=True, null=True)),
                ('ndvi_mean', models.FloatField(blank=True, null=True)),
                ('ndvi_std', models.FloatField(blank=True, null=True)),
                ('ndwi_min', models.FloatField(blank=True, null=True)),
                ('ndwi_max', models.FloatField(blank=True, null=True)),
                ('ndwi_mean', models.FloatField(blank=True, null=True)),
                ('savi_min', models.FloatField(blank=True, null=True)),
                ('savi_max', models.FloatField(blank=True, null=True)),
                ('savi_mean', models.FloatField(blank=True, null=True)),
                ('chemin_ndvi_png', models.CharField(blank=True, max_length=500)),
                ('chemin_ndwi_png', models.CharField(blank=True, max_length=500)),
                ('chemin_savi_png', models.CharField(blank=True, max_length=500)),
                ('interpretation', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='remote_sensing.imagesentinel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
