# Generated by Django 6.0.7 on 2026-07-20 11:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('en_repos', 'En repos'), ('abandonnee', 'Abandonnée')], default='active', max_length=20)),
                ('proprietaire', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('superficie_m2', models.FloatField(blank=True, editable=False, null=True)),
                ('perimetre_m', models.FloatField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
