# Generated by Django 6.0.7 on 2026-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_alter_parcelle_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='type_parcelle',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('zone', 'Zone'), ('parcelle', 'Parcelle')], default='parcelle', max_length=10),
        ),
    ]
