# Generated by Django 6.0.7 on 2026-07-21 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0001_initial'),
        ('palms', '0001_initial'),
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('delai_jours', models.PositiveIntegerField()),
                ('actif', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regles_notification', to='parcels.parcelle')),
                ('type_intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='interventions.typeintervention')),
            ],
            options={
                'ordering': ['type_intervention', 'parcelle'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traitee', 'Traitée'), ('reportee', 'Reportée'), ('ignoree', 'Ignorée')], default='en_attente', max_length=20)),
                ('priorite', models.CharField(choices=[('haute', 'Haute'), ('normale', 'Normale'), ('basse', 'Basse')], default='normale', max_length=10)),
                ('date_echeance', models.DateField()),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('intervention_creee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_origine', to='interventions.intervention')),
                ('palm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='palms.palm')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='parcels.parcelle')),
                ('regle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.reglenotification')),
            ],
            options={
                'ordering': ['-date_echeance', 'priorite'],
            },
        ),
    ]
