# Generated by Django 6.0.7 on 2026-08-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
